// Mock data - ในอนาคตจะดึงจาก API หรือ Database

export const brands = [
  { id: 1, name: "Brand 1", img_url: "https://via.placeholder.com/120x60?text=Brand+1" },
  { id: 2, name: "Brand 2", img_url: "https://via.placeholder.com/120x60?text=Brand+2" },
  { id: 3, name: "Brand 3", img_url: "https://via.placeholder.com/120x60?text=Brand+3" },
  { id: 4, name: "Brand 4", img_url: "https://via.placeholder.com/120x60?text=Brand+4" },
  { id: 5, name: "Brand 5", img_url: "https://via.placeholder.com/120x60?text=Brand+5" },
  { id: 6, name: "Brand 6", img_url: "https://via.placeholder.com/120x60?text=Brand+6" },
  { id: 7, name: "Brand 7", img_url: "https://via.placeholder.com/120x60?text=Brand+7" },
  { id: 8, name: "Brand 8", img_url: "https://via.placeholder.com/120x60?text=Brand+8" },
];

export const collections = [
  {
    id: 1,
    name: "Classic T-Shirt",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+1" },
    starting_price: 599,
  },
  {
    id: 2,
    name: "Denim Jacket",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+2" },
    starting_price: 1299,
  },
  {
    id: 3,
    name: "Casual Pants",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+3" },
    starting_price: 899,
  },
  {
    id: 4,
    name: "Summer Dress",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+4" },
    starting_price: 1499,
  },
  {
    id: 5,
    name: "Leather Jacket",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+5" },
    starting_price: 2499,
  },
  {
    id: 6,
    name: "Cotton Hoodie",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+6" },
    starting_price: 799,
  },
  {
    id: 7,
    name: "Slim Fit Jeans",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+7" },
    starting_price: 1099,
  },
  {
    id: 8,
    name: "Floral Blouse",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+8" },
    starting_price: 699,
  },
];

export const mostPopularCollections = [
  {
    id: 1,
    name: "Best Seller 1",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Best+1" },
    num_orders: 150,
  },
  {
    id: 2,
    name: "Best Seller 2",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Best+2" },
    num_orders: 120,
  },
  {
    id: 3,
    name: "Best Seller 3",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Best+3" },
    num_orders: 98,
  },
  {
    id: 4,
    name: "Best Seller 4",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Best+4" },
    num_orders: 85,
  },
  {
    id: 5,
    name: "Best Seller 5",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Best+5" },
    num_orders: 78,
  },
  {
    id: 6,
    name: "Best Seller 6",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Best+6" },
    num_orders: 65,
  },
  {
    id: 7,
    name: "Best Seller 7",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Best+7" },
    num_orders: 52,
  },
  {
    id: 8,
    name: "Best Seller 8",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Best+8" },
    num_orders: 45,
  },
];

// Categories for explore page
export const categories = [
  { id: 1, name: "Men's Fashion" },
  { id: 2, name: "Women's Fashion" },
  { id: 3, name: "Kids' Fashion" },
  { id: 4, name: "Accessories" },
  { id: 5, name: "Shoes" },
  { id: 6, name: "Bags" },
];

// All collections for explore page (extended list)
export const allCollections = [
  {
    id: 1,
    name: "Classic T-Shirt",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+1" },
    min_price: 599,
    category_id: 1,
    brand_id: 1,
  },
  {
    id: 2,
    name: "Denim Jacket",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+2" },
    min_price: 1299,
    category_id: 1,
    brand_id: 2,
  },
  {
    id: 3,
    name: "Casual Pants",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+3" },
    min_price: 899,
    category_id: 1,
    brand_id: 3,
  },
  {
    id: 4,
    name: "Summer Dress",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+4" },
    min_price: 1499,
    category_id: 2,
    brand_id: 4,
  },
  {
    id: 5,
    name: "Leather Jacket",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+5" },
    min_price: 2499,
    category_id: 1,
    brand_id: 5,
  },
  {
    id: 6,
    name: "Cotton Hoodie",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+6" },
    min_price: 799,
    category_id: 1,
    brand_id: 6,
  },
  {
    id: 7,
    name: "Slim Fit Jeans",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+7" },
    min_price: 1099,
    category_id: 1,
    brand_id: 7,
  },
  {
    id: 8,
    name: "Floral Blouse",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+8" },
    min_price: 699,
    category_id: 2,
    brand_id: 8,
  },
  {
    id: 9,
    name: "Sports Sneakers",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+9" },
    min_price: 1899,
    category_id: 5,
    brand_id: 1,
  },
  {
    id: 10,
    name: "Leather Bag",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+10" },
    min_price: 2299,
    category_id: 6,
    brand_id: 2,
  },
  {
    id: 11,
    name: "Kids T-Shirt",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+11" },
    min_price: 399,
    category_id: 3,
    brand_id: 3,
  },
  {
    id: 12,
    name: "Sunglasses",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+12" },
    min_price: 899,
    category_id: 4,
    brand_id: 4,
  },
  {
    id: 13,
    name: "Winter Coat",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+13" },
    min_price: 3299,
    category_id: 1,
    brand_id: 5,
  },
  {
    id: 14,
    name: "Evening Gown",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+14" },
    min_price: 4599,
    category_id: 2,
    brand_id: 6,
  },
  {
    id: 15,
    name: "Running Shoes",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+15" },
    min_price: 2199,
    category_id: 5,
    brand_id: 7,
  },
  {
    id: 16,
    name: "Backpack",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+16" },
    min_price: 1599,
    category_id: 6,
    brand_id: 8,
  },
  {
    id: 17,
    name: "Polo Shirt",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+17" },
    min_price: 799,
    category_id: 1,
    brand_id: 1,
  },
  {
    id: 18,
    name: "Maxi Skirt",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+18" },
    min_price: 1199,
    category_id: 2,
    brand_id: 2,
  },
  {
    id: 19,
    name: "Baseball Cap",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+19" },
    min_price: 499,
    category_id: 4,
    brand_id: 3,
  },
  {
    id: 20,
    name: "Formal Blazer",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+20" },
    min_price: 2899,
    category_id: 1,
    brand_id: 4,
  },
  {
    id: 21,
    name: "Yoga Pants",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+21" },
    min_price: 899,
    category_id: 2,
    brand_id: 5,
  },
  {
    id: 22,
    name: "Kids Sneakers",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+22" },
    min_price: 799,
    category_id: 3,
    brand_id: 6,
  },
  {
    id: 23,
    name: "Messenger Bag",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+23" },
    min_price: 1899,
    category_id: 6,
    brand_id: 7,
  },
  {
    id: 24,
    name: "Wool Sweater",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+24" },
    min_price: 1499,
    category_id: 1,
    brand_id: 8,
  },
  {
    id: 25,
    name: "Silk Scarf",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+25" },
    min_price: 699,
    category_id: 4,
    brand_id: 1,
  },
  {
    id: 26,
    name: "Chelsea Boots",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+26" },
    min_price: 2599,
    category_id: 5,
    brand_id: 2,
  },
  {
    id: 27,
    name: "Crop Top",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+27" },
    min_price: 599,
    category_id: 2,
    brand_id: 3,
  },
  {
    id: 28,
    name: "Cargo Shorts",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+28" },
    min_price: 799,
    category_id: 1,
    brand_id: 4,
  },
  {
    id: 29,
    name: "Tote Bag",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+29" },
    min_price: 1299,
    category_id: 6,
    brand_id: 5,
  },
  {
    id: 30,
    name: "Winter Gloves",
    primary_image: { image_url: "https://via.placeholder.com/300x400?text=Product+30" },
    min_price: 499,
    category_id: 4,
    brand_id: 6,
  },
];
